"""
Platform-local model registry.

Reads `models/registry.yaml` (generated by tools/build_models.py) rather than
the parent project's `configs/checkpoints.yaml`. Paths are relative to
`models/`, so the whole folder relocates without edits -- that is the point.

Missing checkpoints are SKIPPED rather than raising: a registry entry whose
weights were not copied (or a model still training) must not take the whole
app down. The missing list is surfaced on the Models page instead.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import streamlit as st
import yaml

PLATFORM_ROOT = Path(__file__).resolve().parent.parent
MODELS_ROOT = PLATFORM_ROOT / "models"
REGISTRY_PATH = MODELS_ROOT / "registry.yaml"



@dataclass
class ModelEntry:
    key: str
    display_name: str
    checkpoint: Path
    resolution: int
    family: str = "yolo"
    card: dict[str, Any] = field(default_factory=dict)

    # -- convenience accessors used all over the UI ------------------------

    @property
    def size_mb(self) -> float:
        return float(self.card.get("size_mb") or 0.0)

    @property
    def metrics(self) -> dict[str, Any]:
        return self.card.get("metrics") or {}

    @property
    def training(self) -> dict[str, Any]:
        return self.card.get("training") or {}

    @property
    def map50(self) -> float | None:
        return self.metrics.get("map50")

    @property
    def map50_corrected(self) -> float | None:
        return self.metrics.get("map50_corrected")

    def note(self, lang: str) -> str:
        notes = self.card.get("notes") or {}
        return notes.get(lang) or notes.get("en") or ""

    def short_caption(self) -> str:
        """One line for the picker -- always visible, unlike the hover card."""
        m = self.map50
        acc = f"mAP50 {m * 100:.1f}%" if m is not None else "not measured"
        return f"{acc}  ·  {self.size_mb:.1f} MB  ·  {self.resolution}px"


@st.cache_data(show_spinner=False)
def load_registry() -> tuple[dict[str, ModelEntry], list[str]]:
    """Returns (entries_by_key, missing_keys). Never raises on a bad entry."""
    if not REGISTRY_PATH.exists():
        return {}, ["registry.yaml not found -- run tools/build_models.py"]

    try:
        cfg = yaml.safe_load(REGISTRY_PATH.read_text(encoding="utf-8")) or {}
    except Exception as exc:
        return {}, [f"registry.yaml unreadable: {exc}"]

    entries: dict[str, ModelEntry] = {}
    missing: list[str] = []

    for key, raw in (cfg.get("models") or {}).items():
        ckpt = MODELS_ROOT / raw["checkpoint"]
        if not ckpt.exists():
            missing.append(key)
            continue

        card: dict[str, Any] = {}
        card_rel = raw.get("card")
        if card_rel:
            card_path = MODELS_ROOT / card_rel
            if card_path.exists():
                try:
                    card = json.loads(card_path.read_text(encoding="utf-8"))
                except Exception:
                    card = {}

        entries[key] = ModelEntry(
            key=key,
            display_name=raw.get("display_name", key),
            checkpoint=ckpt,
            resolution=int(raw.get("resolution", 960)),
            family=raw.get("family", "yolo"),
            card=card,
        )

    return entries, missing


def best_key(entries: dict[str, ModelEntry]) -> str | None:
    """Highest corrected mAP50 -- the default selection."""
    scored = [(e.map50_corrected or e.map50 or -1.0, k) for k, e in entries.items()]
    if not scored:
        return None
    return max(scored)[1]
