/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as AuthenticatedVideoRouteImport } from './routes/_authenticated/video'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMyReportRouteImport } from './routes/_authenticated/my-report'
import { Route as AuthenticatedMonitoringRouteImport } from './routes/_authenticated/monitoring'
import { Route as AuthenticatedModelsRouteImport } from './routes/_authenticated/models'
import { Route as AuthenticatedModelRouteImport } from './routes/_authenticated/model'
import { Route as AuthenticatedLiveRouteImport } from './routes/_authenticated/live'
import { Route as AuthenticatedImageRouteImport } from './routes/_authenticated/image'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBenchmarkRouteImport } from './routes/_authenticated/benchmark'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedReportIndexRouteImport } from './routes/_authenticated/report.index'
import { Route as AuthenticatedManagerIndexRouteImport } from './routes/_authenticated/manager.index'
import { Route as AuthenticatedDriverIndexRouteImport } from './routes/_authenticated/driver.index'
import { Route as AuthenticatedReportSessionIdRouteImport } from './routes/_authenticated/report.$sessionId'
import { Route as AuthenticatedManagerHistoryRouteImport } from './routes/_authenticated/manager.history'
import { Route as AuthenticatedManagerAuditRouteImport } from './routes/_authenticated/manager.audit'
import { Route as AuthenticatedDriverReportsRouteImport } from './routes/_authenticated/driver.reports'
import { Route as AuthenticatedManagerDriversIndexRouteImport } from './routes/_authenticated/manager.drivers.index'
import { Route as AuthenticatedManagerDriversDriverIdRouteImport } from './routes/_authenticated/manager.drivers.$driverId'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVideoRoute = AuthenticatedVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyReportRoute = AuthenticatedMyReportRouteImport.update({
  id: '/my-report',
  path: '/my-report',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonitoringRoute = AuthenticatedMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModelsRoute = AuthenticatedModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModelRoute = AuthenticatedModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiveRoute = AuthenticatedLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImageRoute = AuthenticatedImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBenchmarkRoute = AuthenticatedBenchmarkRouteImport.update({
  id: '/benchmark',
  path: '/benchmark',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportIndexRoute =
  AuthenticatedReportIndexRouteImport.update({
    id: '/report/',
    path: '/report/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerIndexRoute =
  AuthenticatedManagerIndexRouteImport.update({
    id: '/manager/',
    path: '/manager/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDriverIndexRoute =
  AuthenticatedDriverIndexRouteImport.update({
    id: '/driver/',
    path: '/driver/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportSessionIdRoute =
  AuthenticatedReportSessionIdRouteImport.update({
    id: '/report/$sessionId',
    path: '/report/$sessionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerHistoryRoute =
  AuthenticatedManagerHistoryRouteImport.update({
    id: '/manager/history',
    path: '/manager/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerAuditRoute =
  AuthenticatedManagerAuditRouteImport.update({
    id: '/manager/audit',
    path: '/manager/audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDriverReportsRoute =
  AuthenticatedDriverReportsRouteImport.update({
    id: '/driver/reports',
    path: '/driver/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerDriversIndexRoute =
  AuthenticatedManagerDriversIndexRouteImport.update({
    id: '/manager/drivers/',
    path: '/manager/drivers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerDriversDriverIdRoute =
  AuthenticatedManagerDriversDriverIdRouteImport.update({
    id: '/manager/drivers/$driverId',
    path: '/manager/drivers/$driverId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/benchmark': typeof AuthenticatedBenchmarkRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/image': typeof AuthenticatedImageRoute
  '/live': typeof AuthenticatedLiveRoute
  '/model': typeof AuthenticatedModelRoute
  '/models': typeof AuthenticatedModelsRoute
  '/monitoring': typeof AuthenticatedMonitoringRoute
  '/my-report': typeof AuthenticatedMyReportRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/video': typeof AuthenticatedVideoRoute
  '/share/$token': typeof ShareTokenRoute
  '/driver/reports': typeof AuthenticatedDriverReportsRoute
  '/manager/audit': typeof AuthenticatedManagerAuditRoute
  '/manager/history': typeof AuthenticatedManagerHistoryRoute
  '/report/$sessionId': typeof AuthenticatedReportSessionIdRoute
  '/driver/': typeof AuthenticatedDriverIndexRoute
  '/manager/': typeof AuthenticatedManagerIndexRoute
  '/report/': typeof AuthenticatedReportIndexRoute
  '/manager/drivers/$driverId': typeof AuthenticatedManagerDriversDriverIdRoute
  '/manager/drivers/': typeof AuthenticatedManagerDriversIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/benchmark': typeof AuthenticatedBenchmarkRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/image': typeof AuthenticatedImageRoute
  '/live': typeof AuthenticatedLiveRoute
  '/model': typeof AuthenticatedModelRoute
  '/models': typeof AuthenticatedModelsRoute
  '/monitoring': typeof AuthenticatedMonitoringRoute
  '/my-report': typeof AuthenticatedMyReportRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/video': typeof AuthenticatedVideoRoute
  '/share/$token': typeof ShareTokenRoute
  '/driver/reports': typeof AuthenticatedDriverReportsRoute
  '/manager/audit': typeof AuthenticatedManagerAuditRoute
  '/manager/history': typeof AuthenticatedManagerHistoryRoute
  '/report/$sessionId': typeof AuthenticatedReportSessionIdRoute
  '/driver': typeof AuthenticatedDriverIndexRoute
  '/manager': typeof AuthenticatedManagerIndexRoute
  '/report': typeof AuthenticatedReportIndexRoute
  '/manager/drivers/$driverId': typeof AuthenticatedManagerDriversDriverIdRoute
  '/manager/drivers': typeof AuthenticatedManagerDriversIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/docs': typeof DocsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/benchmark': typeof AuthenticatedBenchmarkRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/image': typeof AuthenticatedImageRoute
  '/_authenticated/live': typeof AuthenticatedLiveRoute
  '/_authenticated/model': typeof AuthenticatedModelRoute
  '/_authenticated/models': typeof AuthenticatedModelsRoute
  '/_authenticated/monitoring': typeof AuthenticatedMonitoringRoute
  '/_authenticated/my-report': typeof AuthenticatedMyReportRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/video': typeof AuthenticatedVideoRoute
  '/share/$token': typeof ShareTokenRoute
  '/_authenticated/driver/reports': typeof AuthenticatedDriverReportsRoute
  '/_authenticated/manager/audit': typeof AuthenticatedManagerAuditRoute
  '/_authenticated/manager/history': typeof AuthenticatedManagerHistoryRoute
  '/_authenticated/report/$sessionId': typeof AuthenticatedReportSessionIdRoute
  '/_authenticated/driver/': typeof AuthenticatedDriverIndexRoute
  '/_authenticated/manager/': typeof AuthenticatedManagerIndexRoute
  '/_authenticated/report/': typeof AuthenticatedReportIndexRoute
  '/_authenticated/manager/drivers/$driverId': typeof AuthenticatedManagerDriversDriverIdRoute
  '/_authenticated/manager/drivers/': typeof AuthenticatedManagerDriversIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/docs'
    | '/analytics'
    | '/benchmark'
    | '/dashboard'
    | '/history'
    | '/image'
    | '/live'
    | '/model'
    | '/models'
    | '/monitoring'
    | '/my-report'
    | '/profile'
    | '/settings'
    | '/video'
    | '/share/$token'
    | '/driver/reports'
    | '/manager/audit'
    | '/manager/history'
    | '/report/$sessionId'
    | '/driver/'
    | '/manager/'
    | '/report/'
    | '/manager/drivers/$driverId'
    | '/manager/drivers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/docs'
    | '/analytics'
    | '/benchmark'
    | '/dashboard'
    | '/history'
    | '/image'
    | '/live'
    | '/model'
    | '/models'
    | '/monitoring'
    | '/my-report'
    | '/profile'
    | '/settings'
    | '/video'
    | '/share/$token'
    | '/driver/reports'
    | '/manager/audit'
    | '/manager/history'
    | '/report/$sessionId'
    | '/driver'
    | '/manager'
    | '/report'
    | '/manager/drivers/$driverId'
    | '/manager/drivers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/docs'
    | '/_authenticated/analytics'
    | '/_authenticated/benchmark'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/image'
    | '/_authenticated/live'
    | '/_authenticated/model'
    | '/_authenticated/models'
    | '/_authenticated/monitoring'
    | '/_authenticated/my-report'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/video'
    | '/share/$token'
    | '/_authenticated/driver/reports'
    | '/_authenticated/manager/audit'
    | '/_authenticated/manager/history'
    | '/_authenticated/report/$sessionId'
    | '/_authenticated/driver/'
    | '/_authenticated/manager/'
    | '/_authenticated/report/'
    | '/_authenticated/manager/drivers/$driverId'
    | '/_authenticated/manager/drivers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DocsRoute: typeof DocsRoute
  ShareTokenRoute: typeof ShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/video': {
      id: '/_authenticated/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof AuthenticatedVideoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-report': {
      id: '/_authenticated/my-report'
      path: '/my-report'
      fullPath: '/my-report'
      preLoaderRoute: typeof AuthenticatedMyReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitoring': {
      id: '/_authenticated/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AuthenticatedMonitoringRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/models': {
      id: '/_authenticated/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AuthenticatedModelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/model': {
      id: '/_authenticated/model'
      path: '/model'
      fullPath: '/model'
      preLoaderRoute: typeof AuthenticatedModelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live': {
      id: '/_authenticated/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AuthenticatedLiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/image': {
      id: '/_authenticated/image'
      path: '/image'
      fullPath: '/image'
      preLoaderRoute: typeof AuthenticatedImageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/benchmark': {
      id: '/_authenticated/benchmark'
      path: '/benchmark'
      fullPath: '/benchmark'
      preLoaderRoute: typeof AuthenticatedBenchmarkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/': {
      id: '/_authenticated/report/'
      path: '/report'
      fullPath: '/report/'
      preLoaderRoute: typeof AuthenticatedReportIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/': {
      id: '/_authenticated/manager/'
      path: '/manager'
      fullPath: '/manager/'
      preLoaderRoute: typeof AuthenticatedManagerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/driver/': {
      id: '/_authenticated/driver/'
      path: '/driver'
      fullPath: '/driver/'
      preLoaderRoute: typeof AuthenticatedDriverIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/$sessionId': {
      id: '/_authenticated/report/$sessionId'
      path: '/report/$sessionId'
      fullPath: '/report/$sessionId'
      preLoaderRoute: typeof AuthenticatedReportSessionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/history': {
      id: '/_authenticated/manager/history'
      path: '/manager/history'
      fullPath: '/manager/history'
      preLoaderRoute: typeof AuthenticatedManagerHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/audit': {
      id: '/_authenticated/manager/audit'
      path: '/manager/audit'
      fullPath: '/manager/audit'
      preLoaderRoute: typeof AuthenticatedManagerAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/driver/reports': {
      id: '/_authenticated/driver/reports'
      path: '/driver/reports'
      fullPath: '/driver/reports'
      preLoaderRoute: typeof AuthenticatedDriverReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/drivers/': {
      id: '/_authenticated/manager/drivers/'
      path: '/manager/drivers'
      fullPath: '/manager/drivers/'
      preLoaderRoute: typeof AuthenticatedManagerDriversIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/drivers/$driverId': {
      id: '/_authenticated/manager/drivers/$driverId'
      path: '/manager/drivers/$driverId'
      fullPath: '/manager/drivers/$driverId'
      preLoaderRoute: typeof AuthenticatedManagerDriversDriverIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBenchmarkRoute: typeof AuthenticatedBenchmarkRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedImageRoute: typeof AuthenticatedImageRoute
  AuthenticatedLiveRoute: typeof AuthenticatedLiveRoute
  AuthenticatedModelRoute: typeof AuthenticatedModelRoute
  AuthenticatedModelsRoute: typeof AuthenticatedModelsRoute
  AuthenticatedMonitoringRoute: typeof AuthenticatedMonitoringRoute
  AuthenticatedMyReportRoute: typeof AuthenticatedMyReportRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedVideoRoute: typeof AuthenticatedVideoRoute
  AuthenticatedDriverReportsRoute: typeof AuthenticatedDriverReportsRoute
  AuthenticatedManagerAuditRoute: typeof AuthenticatedManagerAuditRoute
  AuthenticatedManagerHistoryRoute: typeof AuthenticatedManagerHistoryRoute
  AuthenticatedReportSessionIdRoute: typeof AuthenticatedReportSessionIdRoute
  AuthenticatedDriverIndexRoute: typeof AuthenticatedDriverIndexRoute
  AuthenticatedManagerIndexRoute: typeof AuthenticatedManagerIndexRoute
  AuthenticatedReportIndexRoute: typeof AuthenticatedReportIndexRoute
  AuthenticatedManagerDriversDriverIdRoute: typeof AuthenticatedManagerDriversDriverIdRoute
  AuthenticatedManagerDriversIndexRoute: typeof AuthenticatedManagerDriversIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBenchmarkRoute: AuthenticatedBenchmarkRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedImageRoute: AuthenticatedImageRoute,
  AuthenticatedLiveRoute: AuthenticatedLiveRoute,
  AuthenticatedModelRoute: AuthenticatedModelRoute,
  AuthenticatedModelsRoute: AuthenticatedModelsRoute,
  AuthenticatedMonitoringRoute: AuthenticatedMonitoringRoute,
  AuthenticatedMyReportRoute: AuthenticatedMyReportRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedVideoRoute: AuthenticatedVideoRoute,
  AuthenticatedDriverReportsRoute: AuthenticatedDriverReportsRoute,
  AuthenticatedManagerAuditRoute: AuthenticatedManagerAuditRoute,
  AuthenticatedManagerHistoryRoute: AuthenticatedManagerHistoryRoute,
  AuthenticatedReportSessionIdRoute: AuthenticatedReportSessionIdRoute,
  AuthenticatedDriverIndexRoute: AuthenticatedDriverIndexRoute,
  AuthenticatedManagerIndexRoute: AuthenticatedManagerIndexRoute,
  AuthenticatedReportIndexRoute: AuthenticatedReportIndexRoute,
  AuthenticatedManagerDriversDriverIdRoute:
    AuthenticatedManagerDriversDriverIdRoute,
  AuthenticatedManagerDriversIndexRoute: AuthenticatedManagerDriversIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DocsRoute: DocsRoute,
  ShareTokenRoute: ShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
